### PR TITLE
Feature/autocapitals

### PR DESCRIPTION
**Pull request by ZetaSmile**
Changelog:
* card name and subtitle are now automatically converted to uppercase

### CODE REVIEW

**Comment by DanudeSandstorm** [comment]
Hey there! I appreciate the PR, I ended up taking this idea and making it an option instead (default is on). Thanks for using the card creator

**Comment by ZetaSmile** [comment]
Hi, I'm glad to hear it. Apologies for the weird PR, it's been a while since I used GitHub. I wasn't sure if you were still working on this, so I tried to fork it at the time.

Would it be fine for me to contribute to this repo directly? There are a couple of minor changes I'd like to see added in the card creator besides the auto-caps.

**Comment by DanudeSandstorm** [comment]
I rather have you go through the PR process so I can review

**Comment by ZetaSmile** [comment]
Oh no I plan to; to clarify I just meant I'd like to branch off this repo instead of working solely on the fork I opened.

Anyway sounds good! I'll set up a couple of notes in the issue section to list potential additions.

**Pull request closed without merging**
